### ISSUE TITLE
FW 2019.4 and higher not supported

### ISSUE THREAD

**Issue by sonicxnet** [jnuyens/freedomev#9]
Can give a overview why FreedomEV isn't working on cars with firmware from 2019.4?

**Comment by mystcat** [comment]
No cron

**Comment by jnuyens** [comment]
Tesla is mounting a tmpfs over /var/spool/crontab
For this version and higher, you need to ensure this tmps gets unmounted to freedomev work again.
We don't provide the workaround here to prevent Tesla from closing that (we prefer that this will not become a cat and mouse game).

Such a cat and mouse game would mean that eventually we have no other option than to build a complete patched filesystem image. One of the objectives of FreedomEV is to make it as non-intrusive as possible, and this would go against that direction.

We might eventually have no other option (as we have the impression that Tesla is closing more and more access). The ideal situation would be if there would be a 'Tesla approved' way to get root access on your own car (for security researchers and developers).

Some people fear that things are moving in the opposite direction; where Tesla is turning the cars more and more into systems where nothing can be changed without their approval and where they have a lot more possibilities with the cars than the real owners. Let's hope Tesla does not forget who is actually owning the cars and does the right thing.

**Comment by ErikDeBruijn** [comment]
With Ultimaker 3D printers (which also run Linux) you can select "Developer mode" on the device and it will enable ssh on port 22. Ultimaker once in a while incorporates changes that people have been able to use, prove the usefulness of and share with others (which demonstrates market interest). So it would make sense for Tesla to do the same, save for perhaps the autopilot computer.

By the way @jnuyens , are we 100% sure that everything before 2019.4 is not mounting tmpfs over the crontab? Because I'm still on 2018.48.12.1, quite an ancient release, actually...

**Comment by verygreen** [comment]
Yes, this change was introduced in 19.4 firmware, all prior ones have access to permanent storage in /var/spool/cron

As such you definitely can use it on 18.48.12.1

**Comment by 0x77dev** [comment]
Is there a way to downgrade?

**Comment by Baha2Odeh** [comment]
Are you sure we can use 2019.36.2 ? I have 2019.36.2 and cron mounted on swap
